baseURL = "https://example.com"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Planet EasyPeasy"
theme = "lightbi-hugo"
summaryLength  = "30"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = ""
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = true
readingTime = true
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true 
gcse = false
Lastmod = false
rss = true 
pagination = "10"
hideAuthor = false
authorInfo = "Cuttin' through the space junk"
description="Your can add your website description here."
lunrSearch = true
previewCardImagePlacement = "top"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[author]
  name = "Cosmocrat Aspen Nebula"
  website = "https://binovarghese.com"
  email = "sample@gmail.com"
  facebook = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  twitter = "username"
  linkedin = "username"
  threads = "username"
  reddit = "username"
  snapchat = "username"
  paypal = "username"
  telegram = "username"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3


[[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5



tags = [
  "blog", 
  "bootstrap",
  "bootstrap icons",
  "company",
  "dark",
  "dark mode",
  "light",
  "minimal",
  "multilingual",
  "portfolio", 
  "responsive",
  "personal","tag1","tag2","tag3"
  ]
